import Banner from "@/components/Banner"
import AboutMe from "@/components/homepage/AboutMe"
import Services from "@/components/homepage/Services"
import Layout from "@/components/layout/Layout"
import CallNowSection1 from "@/components/small-components/CallNowSection1"
import Head from "next/head"

export const AboutMePage = () => {
  return (
    <>
      <Head>
        <title>Rólam | Dorin Kozmetika - Győr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <Banner text="Üdvözöllek" bg="aboutme-bg" />
          <AboutMe />
        </Layout>
      </main>
    </>
  )
}

export default AboutMePage
