import Banner from "@/components/Banner"
import Contact from "@/components/Contact"
import Layout from "@/components/layout/Layout"
import CallNowSection1 from "@/components/small-components/CallNowSection1"
import Head from "next/head"

export const ContactPage = () => {
  return (
    <>
      <Head>
        <title>Elérhetőségek | Dorin Kozmetika - Győr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <Banner text="Lépj velem kapcsolatba" bg="elerhetosegek-bg" />
          <Contact />
          <CallNowSection1 />
        </Layout>
      </main>
    </>
  )
}

export default ContactPage
