import Head from "next/head"
import { Inter } from "next/font/google"
import Layout from "@/components/layout/Layout"
import MainBanner from "@/components/homepage/MainBanner"
import AboutMe from "@/components/homepage/AboutMe"
import Services from "@/components/homepage/Services"
import Brands from "@/components/homepage/Brands"
import Giftcard from "@/components/homepage/Giftcard"
import ImageGalery from "@/components/homepage/ImageGalery"
import CallNowSection1 from "@/components/small-components/CallNowSection1"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <MainBanner />
          <AboutMe />
          <Services />
          <Brands />
          <Giftcard />
          <ImageGalery />
          <CallNowSection1 />
        </Layout>
      </main>
    </>
  )
}
